version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - 12000:3000
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
# /33wwwwwww
    ports:
      - 12001:80
    restart: always
