version: "3.7"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile

        ports:
            - 12000:3001
        restart: always

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile

        ports:
            - 12001:80
        restart: always
    cliente:
        build:
            context: ./cliente
            dockerfile: Dockerfile

        ports:
            - 12002:80
        restart: always
