name: Teste tando aplicação no backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    environment:
      name: VPSLAREAN
      url: https://apiagendamento.larean.com.br

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configurar o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Instalar Dependências do Backend
        working-directory: backend
        run: npm install

      - name: Buildando Backend
        working-directory: backend
        run: npm run build     
      
      - name: iniciando aplicação para teste
        working-directory: backend
        run: npm run play & sleep 10s




